server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:myNote.p12
        key-store-password: myNoteHttps
        key-store-type: PKCS12
        key-alias: myNote

spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/workspace/myNote/myNote
        driver-class-name: org.h2.Driver
        username: sa
